name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.4
          args: --timeout=10m